#!/bin/bash -e

PATH=$(pwd)/bin:${PATH}

function collect_includes() {
    local includes=()
    for file in $@
    do
        # get directory with trailing slash
        local dir=$(dirname ${file})
        dir="${dir%/}/"

        # find includes
        local file_includes=($(yq eval '.includes // [] | @csv' ${file}))

        # recusively collect includes
        if [ -n ${file_includes} ]
        then
            file_includes=("${file_includes[@]/#/${dir}}")
            includes+=("${file_includes}")
            includes+=("$(collect_includes ${file_includes})")
        fi
    done

    printf "%s\n" "${includes[@]}"
}

for template in $(find templates -type f -maxdepth 1)
do
    echo ${template}

    # merge template with includes
    yq eval-all '. as $item ireduce ({}; . *+ $item )' ${template} $(collect_includes ${template}) | \
    # explode anchors and remove fragments and includes
    yq eval 'explode(.) | del (.fragments) | del(.includes)' - \
    > .github/workflows/$(basename ${template})
done