#!/bin/bash -e

templates="deploy.yaml"

for template in $(ls templates | grep -v fragments.yaml)
do
    echo ${template}
    cat templates/fragments.yaml templates/${template} | yq eval 'explode(.) | del (.fragments)' - > .github/workflows/${template}
done