#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.all
---
jobs:
  #@overlay/match by=overlay.map_key("uses"), when=1
  _:
    uses: "goes-funky/workflows/.github/workflows/build-python.yaml@master"
    #@overlay/match missing_ok=True
    permissions:
      #@overlay/match missing_ok=True
      contents: read
      #@overlay/match missing_ok=True
      id-token: write
      actions: write
    secrets:
      #@overlay/match missing_ok=True
      #@overlay/remove
      gcp-gcr-project-id: ''
      #@overlay/match when=1
      gcp-gcr-workload-identity-provider: ${{ secrets.GCP_GCR_WORKLOAD_IDENTITY_PROVIDER }}
