fragments:
  step-checkout: &step-checkout
    name: Checkout
    if: "!inputs.skip-checkout"
    uses: actions/checkout@v2
on:
  workflow_call:
    inputs:
      skip-checkout:
        type: boolean
        description: Whether to skip checkout
        default: false
