includes:
  - ssh-agent.yaml

on:
  workflow_call:
    secrets:
      ssh-private-key:
        description: SSH private key used to authenticate to GitHub with, in order to fetch private dependencies
        required: false