# Dependencies: templates/common/deploy.yaml templates/common/ssh-agent.yaml
name: Deploy
fragments:
  step-setup-ssh-agent: &step-setup-ssh-agent
on:
  workflow_call:
    inputs:
      development-branch:
        type: string
        description: "Development branch"
        default: "${{ github.event.repository.default_branch }}"
        required: false
env:
  SKAFFOLD_PUSH: "$${ github.event.ref == format('refs/heads/{0}', inputs.development-branch) || github.event.action == 'released' }"
jobs:
  # deploy to development from default branch or tagged release
  deploy-development:
    if: "!inputs.skip-deploy && (github.event.ref == format('refs/heads/{0}', inputs.development-branch) || github.event.action == 'released')"
  # deploy to production from tagged release
  deploy-production:
    if: "!inputs.skip-deploy && github.event.action == 'released'"
