# Dependencies: templates/common/deploy.yaml templates/common/ssh-agent.yaml
name: Deploy
fragments:
  step-setup-ssh-agent: &step-setup-ssh-agent
on:
jobs:
  # build from develop or master branch
  build: 
    if: "github.event.ref == 'refs/heads/develop' || github.event.ref == 'refs/heads/master'"
  # deploy to development from develop or master branch
  deploy-development:
    if: "!inputs.skip-deploy && (github.event.ref == 'refs/heads/develop' || github.event.ref == 'refs/heads/master')"
  # deploy to production from master branch
  deploy-production:
    if: "!inputs.skip-deploy && github.event.ref == 'refs/heads/master'"