name: Deploy

on:
  !!merge: <<: *workflow-call-deploy

jobs:
  build: 
    name: Build Docker images
    if: "github.event.ref == 'refs/heads/master' || github.event.ref == 'refs/heads/develop'"
    !!merge <<: *job-build

  deploy-environment:
    name: Deploy to environment
    if: "!inputs.skip-deploy && inputs.environment"
    needs: [build]
    environment: ${{ inputs.environment }}
    !!merge <<: *job-deploy

  deploy-development:
    name: Deploy to development
    if: "!inputs.skip-deploy && (github.event.ref == 'refs/heads/master' || github.event.ref == 'refs/heads/develop')"
    needs: [build]
    environment: development
    !!merge <<: *job-deploy

  deploy-production:
    name: Deploy to production
    if: "!inputs.skip-deploy && github.event.ref == 'refs/heads/master'"
    needs: [build, deploy-development]
    environment: production
    !!merge <<: *job-deploy