# Dependencies: templates/common/deploy.yaml templates/common/ssh-agent.yaml
name: Deploy
fragments:
  step-setup-ssh-agent: &step-setup-ssh-agent
on:
  workflow_call:
    inputs:
      development-branch:
        type: string
        description: "Development branch"
        default: ""
        required: false
jobs:
  # deploy to development from default branch or tagged release
  deploy-development:
    if: "!inputs.skip-deploy && (github.event.ref == format('refs/heads/{0}', github.event.repository.default_branch) || startsWith(github.event.ref, 'refs/tags/v') || github.event.ref == format('refs/heads/{0}', inputs.development-branch))"
  # deploy to production from tagged release
  deploy-production:
    if: "!inputs.skip-deploy && startsWith(github.event.ref, 'refs/tags/v')"
