name: Build Python

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: Python version
        default: "3.9"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      PIPENV_VERBOSITY: "-1"
      PIPENV_VENV_IN_PROJECT: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Setup pipenv
        run: python -m pip install pipenv

      - name: Setup cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            .venv/
          key: ${{ runner.os }}-python-${{ inputs.python-version }}-${{ hashFiles('**/Pipfile.lock') }}

      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pipenv install --dev --deploy

      - name: Ensure code is formatted
        run: pipenv run format && git diff --quiet --exit-code

      - name: Lint
        run: pipenv run lint

      - name: Unit test
        run: pipenv run test

      - name: Integration test
        run: pipenv run integration-test
