name: Build Go

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: Go version
        default: "1.17"
    secrets:
      ssh-private-key:
        description: SSH private key used to authenticate to GitHub with, in order to fetch private dependencies
        required: false

jobs:
  tools:
    runs-on: ubuntu-latest
    name: Tools
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup tools cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            build/
          key: "${{ runner.os }}-tools-${{ hashFiles('Makefile', 'makefiles/**') }}"

      - name: Setup go
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v2
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Download tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: make tools

  deps:
    runs-on: ubuntu-latest
    name: Dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: Setup Go cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: "${{ runner.os }}-deps-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}""

      - name: Setup Go
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-go@v2
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: "${{ secrets.ssh-private-key }}"

      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          go mod download

  check:
    needs: [tools, deps]
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Setup tools cache
        uses: actions/cache@v2
        with:
          path: |
            build/
          key: "${{ runner.os }}-tools-${{ hashFiles('Makefile', 'makefiles/**') }}"

      - name: Setup go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: "${{ runner.os }}-deps-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}"

      - name: Ensure code is formatted
        run: make format && make git-dirty

      - name: Lint
        run: GOLANGCILINT_CONCURRENCY=4 make lint

  test:
    needs: [tools, deps]
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Setup tools cache
        uses: actions/cache@v2
        with:
          path: |
            build/
          key: "${{ runner.os }}-tools-${{ hashFiles('Makefile', 'makefiles/**') }}"

      - name: Setup go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: "${{ runner.os }}-deps-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}"

      - name: Unit test with coverage
        run: make test-coverage

      - name: Integration test
        run: make integration-test
