name: Deploy

on:
  workflow_call:
    inputs:
      skaffold:
        type: string
        description: "Skaffold Version"
        default: "1.33.0"
    secrets:
      GCP_PROJECT_ID:
        description: "GCP Project ID"
        required: true
      GCP_SERVICE_ACCOUNT:
        description: "GCP Service Account Key"
        required: true
      GKE_CLUSTER:
        description: "GKE Cluster Name"
        required: true
      GKE_LOCATION:
        description: "GKE Cluster Location"
        required: true

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Configure Docker Auth
        run: |
          gcloud --quiet auth configure-docker eu.gcr.io

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: "skaffold"
          skaffold: "${{ inputs.skaffold }}"

      - name: Build
        run: |
          skaffold build
