name: Build Go

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: Go version
        default: "1.17"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Setup tools cache
        uses: actions/cache@v2
        with:
          path: |
            build/
          key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}

      - name: Setup go cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}

      - name: Download dependencies
        run: make deps

      - name: Ensure code is formatted
        run: make format && make git-dirty

      - name: Lint
        run: GOLANGCILINT_CONCURRENCY=4 make lint

      - name: Unit test with coverage
        run: make test-coverage

      - name: Integration test
        run: make integration-test
