name: Build Go

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        description: Go version
        default: "1.17"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            build/
          key: ${{ runner.os }}-go-${{ inputs.go-version }}-${{ hashFiles('**/go.sum', 'Makefile') }}

      - name: Download dependencies
        run: make deps

      - name: Pack built code
        run: tar -cvf build.tar .

      - name: Upload built code
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build.tar

  tests:
    runs-on: ubuntu-latest
    name: Tests
    needs: build
    env:
      GOLANGCILINT_CONCURRENCY: 4
    strategy:
      matrix:
        test:
          - make lint
          - make test-coverage
          - make format && make git-dirty
          - make integration-test
    steps:
      - name: Download built code
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Unpack build code
        run: tar -xvf build.tar

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ inputs.go-version }}"

      - name: Run the test
        run: ${{ matrix.test }}
