name: Build Python

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: Python version
        default: "3.9"
      poetry-version:
        type: string
        description: Poetry version
        default: "1.1.12"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "${{ inputs.poetry-version }}"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Setup cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            .venv/
          key: ${{ runner.os }}-python-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Download dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Ensure code is formatted
        run: pipenv run format && git diff --quiet --exit-code

      - name: Lint
        run: pipenv run lint

      - name: Unit test
        run: pipenv run test

      - name: Integration test
        run: pipenv run integration-test
