name: Build Python
on:
  workflow_call:
    inputs:
      python-version:
        type: string
        description: Python version
        default: "3.9"
      poetry-version:
        type: string
        description: Poetry version
        default: "1.1.12"
      skip-lint:
        type: boolean
        description: Whether to skip code linting
        default: false
      skip-format:
        type: boolean
        description: Whether to skip code formatting
        default: false
      skip-checkout:
        type: boolean
        description: Whether to skip checkout
        default: false
      skip-tests:
        type: boolean
        description: Whether to skip running tests
        default: false
    secrets:
      ssh-private-key:
        description: SSH private key used to authenticate to GitHub with, in order to fetch private dependencies
        required: true
      codecov-token:
        description: Token to upload coverage reports to codecov
        required: false
jobs:
  deps:
    runs-on: ubuntu-latest
    name: Dependencies
    steps:
      - name: Checkout
        if: "!inputs.skip-checkout"
        uses: actions/checkout@v2
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"
      - name: Setup cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: |
            .venv/
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "${{ inputs.poetry-version }}"
          virtualenvs-create: true
          virtualenvs-in-project: true
        if: "!steps.deps-cache.outputs.cache-hit"
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: "${{ secrets.ssh-private-key }}"
        if: "!steps.deps-cache.outputs.cache-hit"
      - name: Download dependencies
        if: "!steps.deps-cache.outputs.cache-hit"
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          poetry install
  black:
    needs: [deps]
    runs-on: ubuntu-latest
    name: Black
    if: "!inputs.skip-format"
    steps:
      - name: Checkout
        if: "!inputs.skip-checkout"
        uses: actions/checkout@v2
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"
      - name: Setup cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: |
            .venv/
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "${{ inputs.poetry-version }}"
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Ensure code is formatted
        run: poetry run black --check .

  lint:
    needs: [deps]
    runs-on: ubuntu-latest
    name: Lint
    if: "!inputs.skip-lint"
    steps:
      - name: Checkout
        if: "!inputs.skip-checkout"
        uses: actions/checkout@v2
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"
      - name: Setup cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: |
            .venv/
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "${{ inputs.poetry-version }}"
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Lint
        run: poetry run flake8

  coverage:
    needs: [deps]
    runs-on: ubuntu-latest
    if: "!inputs.skip-tests"
    name: Coverage
    steps:
      - name: Checkout
        if: "!inputs.skip-checkout"
        uses: actions/checkout@v2
      - name: Setup python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ inputs.python-version }}"
      - name: Setup cache
        id: deps-cache
        uses: actions/cache@v2
        with:
          path: |
            .venv/
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "${{ inputs.poetry-version }}"
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage xml
      - name: Upload Coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.codecov-token }}
        if: env.CODECOV_TOKEN != null
        uses: codecov/codecov-action@v2
        with:
          token: "${{ secrets.codecov-token }}"
          file: ./coverage.xml
          yml: ./codecov.yml
