name: Deploy
"on":
  workflow_call:
    inputs:
      skaffold:
        type: string
        description: Skaffold version
        default: 1.33.0
      kubeval:
        type: string
        description: Kubeval version
        default: 0.16.1
      environment:
        type: string
        description: Deployment environment
        required: false
      development-environment:
        type: string
        description: Development environment
        default: dev
        required: false
      production-environment:
        type: string
        description: Production environment
        default: prod
        required: false
      default-repo:
        type: string
        description: Default artifact repository
        default: eu.gcr.io/y42-artifacts-ea47981a
      dist-ar --build-artifacts=build.json
