name: Deploy
"on":
  workflow_call:
    inputs:
      environment:
        type: string
        description: Deployment environment
        required: false
      development-environment:
        type: string
        description: Development environment
        default: dev
        required: false
      production-environment:
        type: string
        description: Production environment
        default: prod
        required: false
      default-repo:
        type: string
        description: Default artifact repository
        default: eu.gcr.io/y42-artifacts-ea47981a
      dist-artifact:
        type: string
        description: Dist artifact name
        required: false
      untar-artifact-name:
        type: string
        description: Name of the input artifact to untar
        required: false
      skip-deploy:
        type: boolean
        description: Skip deployment to cluster
        required: false
      skaffold-file:
        type: string
        description: Skaffold file to use
        default: skaffold.yaml
      docker-file:
        type: string
        description: Docker file to use
        default: Dockerfile
      skip-checkout:
        type: boolean
        description: Whether to skip checkout
        default: false
      skaffold:
        type: string
        description: Skaffold version
        default: 1.39.2
      is-repo-public:
        type: boolean
        description: Whether to skip ssh agent configuration
        default: false
      development-branch:
        type: string
        description: Development branch
        default: develop
        required: false
      use-skaffold-cache:
        type: boolean
        required: false
        default: true
        description: Setup skaffold cache before build
      with-submodules:
        type: boolean
        description: Whether to fetch git submodules
        default: false
      kubeval:
        type: string
        description: Kubeval version
        default: 0.16.1
      production-branch:
        type: string
        description: Production branch
        default: master
        required: false
    secrets:
      gcp-service-account:
        description: GCP Service Account e-mail, has permission to artifact repo
        required: true
      gcp-workload-identity-provider:
        description: GCP Workload Identity provider
        required: true
      gcp-gcr-service-account:
        description: GCP GCR Service Account e-mail
        required: true
      gke-cluster:
        description: GKE Cluster Name
        required: true
      ssh-private-key:
        description: SSH private key used to authenticate to GitHub with, in order to fetch private dependencies
        required: false
      gcp-gcr-workload-identity-provider:
        description: GCP GCR Workload Identity provider
        required: true
      gke-location:
        description: GKE Cluster Location (ignored in lieu of fully-qualified cluster ID)
        required: false
env:
  SKAFFOLD_PUSH: $${ github.event.ref == format('refs/heads/{0}', inputs.development-branch) || github.event.ref == format('refs/heads/{0}', inputs.production-branch)}
jobs:
  deploy-development:
    needs:
      - build
    if: '!inputs.skip-deploy && (github.event.ref == format(''refs/heads/{0}'', inputs.development-branch) || github.event.ref == format(''refs/heads/{0}'', inputs.production-branch))'
    environment: ${{ inputs.development-environment }}
    runs-on: ubuntu-latest
    name: Deploy to development
    timeout-minutes: 15
    steps:
      - name: Checkout
        if: '!inputs.skip-checkout'
        uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.with-submodules }}
      - name: Authenticate to Google Cloud
        id: auth_gcp
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.gcp-service-account }}
          workload_identity_provider: ${{ secrets.gcp-workload-identity-provider }}
          token_format: access_token
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.gke-cluster }}
      - name: Download build reference
        uses: actions/download-artifact@v3
        with:
          name: build-${{ inputs.skaffold-file }}
      - name: Setup Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: skaffold
          skaffold: ${{ inputs.skaffold }}
      - name: Deploy
        run: skaffold deploy --filename=${{ inputs.skaffold-file }} --profile nonprod --force --build-artifacts=build.json
  deploy-production:
    needs:
      - build
      - deploy-development
    if: '!inputs.skip-deploy && github.event.ref == format(''refs/heads/{0}'', inputs.production-branch)'
    environment: ${{ inputs.production-environment }}
    runs-on: ubuntu-latest
    name: Deploy to production
    timeout-minutes: 15
    steps:
      - name: Checkout
        if: '!inputs.skip-checkout'
        uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.with-submodules }}
      - name: Authenticate to Google Cloud
        id: auth_gcp
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.gcp-service-account }}
          workload_identity_provider: ${{ secrets.gcp-workload-identity-provider }}
          token_format: access_token
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.gke-cluster }}
      - name: Download build reference
        uses: actions/download-artifact@v3
        with:
          name: build-${{ inputs.skaffold-file }}
      - name: Setup Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: skaffold
          skaffold: ${{ inputs.skaffold }}
      - name: Deploy
        run: skaffold deploy --filename=${{ inputs.skaffold-file }} --profile prod --force --build-artifacts=build.json
  build:
    runs-on: ubuntu-latest
    name: Build Docker images
    timeout-minutes: 20
    steps:
      - name: Checkout
        if: '!inputs.skip-checkout'
        uses: actions/checkout@v3
        with:
          path: ./code
      - name: Setup buildkit
        id: setup-buildkit
        uses: docker/setup-buildx-action@v2
      - name: Setup skaffold cache
        if: inputs.use-skaffold-cache
        uses: actions/cache@v3
        with:
          path: ~/.skaffold/cache
          key: ${{ runner.os }}-skaffold-${{ github.sha }}
          restore-keys: |-
            ${{ runner.os }}-skaffold-${{ github.sha }}
            ${{ runner.os }}-skaffold
      - uses: actions/download-artifact@v3
        if: inputs.dist-artifact
        with:
          name: ${{ inputs.dist-artifact }}
          path: ./code/dist
      - name: Expose Github Action runtime
        uses: actions/github-script@v6
        with:
          script: |-
            try {
                Object.keys(process.env).forEach(function (key) {
                    if (key.startsWith('ACTIONS_')) {
                        core.info(`${key}=${process.env[key]}`);
                        core.exportVariable(key, process.env[key]);
                    }
                });
            } catch (error) {
                core.setFailed(error.message);
            }
      - name: Download custom skaffold docker build script
        run: curl -LsO https://raw.githubusercontent.com/goes-funky/workflows/master/scripts/docker-buildx && chmod +x docker-buildx
      - name: Configure skaffold to build with buildkit
        run: 'cp ./code/${{ inputs.skaffold-file }} . && yq -i ''del(.build.local) | del(.build.artifacts.[].docker) | del(.build.artifacts.[].sync.*) | .build.artifacts.[] *= {"custom": {"buildCommand": "../docker-buildx", "dependencies": {"dockerfile": {"path": "${{ inputs.docker-file }}"}}}}'' ${{ inputs.skaffold-file }}'
      - name: Untar build artifact
        if: inputs.untar-artifact-name
        run: tar -xf ./code/dist/${{ inputs.untar-artifact-name }} -C ./code/dist
      - name: Setup SSH Agent
        if: '!inputs.is-repo-public'
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ssh-private-key }}
      - name: Authenticate to Google Cloud
        id: auth_gcp
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.gcp-gcr-service-account }}
          workload_identity_provider: ${{ secrets.gcp-gcr-workload-identity-provider }}
      - name: Authenticate to Google Container Registry
        id: auth_gcr
        uses: docker/login-action@v2
        with:
          registry: eu.gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth_gcp.outputs.access_token }}
      - name: Authenticate to Google Artifact Registry
        id: auth_docker_pkg_dev
        uses: docker/login-action@v2
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth_gcp.outputs.access_token }}
      - name: Setup Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |-
            skaffold
            kubeval
          skaffold: ${{ inputs.skaffold }}
          kubeval: ${{ inputs.kubeval }}
      - name: Configure Skaffold
        run: skaffold config set default-repo "${{ inputs.default-repo }}"
      - name: Export git build details
        run: |-
          CONTAINER_NAME=$(cd ./code && basename -s .git "$(git remote get-url origin)") && echo "CONTAINER_NAME=$CONTAINER_NAME" >> "$GITHUB_ENV"
          SHORT_SHA="$(git -C ./code rev-parse --short HEAD)" && echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"
      - name: Build
        env:
          SKAFFOLD_DEFAULT_REPO: ${{ inputs.default-repo }}
          SKAFFOLD_CACHE_ARTIFACTS: ${{ inputs.use-skaffold-cache }}
          DOCKER_BUILDKIT_BUILDER: ${{ steps.setup-buildkit.outputs.name }}
          CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
          SHORT_SHA: ${{ env.SHORT_SHA }}
        run: cd ./code && skaffold build --filename=../${{ inputs.skaffold-file }} --file-output=build.json
      - name: Archive build reference
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ inputs.skaffold-file }}
          path: ./code/build.json
  deploy-environment:
    needs:
      - build
    if: inputs.environment
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    name: Deploy to environment
    timeout-minutes: 15
    steps:
      - name: Checkout
        if: '!inputs.skip-checkout'
        uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.with-submodules }}
      - name: Authenticate to Google Cloud
        id: auth_gcp
        uses: google-github-actions/auth@v1
        with:
          service_account: ${{ secrets.gcp-service-account }}
          workload_identity_provider: ${{ secrets.gcp-workload-identity-provider }}
          token_format: access_token
      - uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.gke-cluster }}
      - name: Download build reference
        uses: actions/download-artifact@v3
        with:
          name: build-${{ inputs.skaffold-file }}
      - name: Setup Kubernetes tools
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: skaffold
          skaffold: ${{ inputs.skaffold }}
      - name: Deploy
        env:
          SKAFFOLD_PROFILE: ${{ (inputs.environment == inputs.production-environment) && 'prod' || 'nonprod' }}
        run: skaffold deploy --filename=${{ inputs.skaffold-file }} --force --build-artifacts=build.json
