name: Deploy

on:
  workflow_call:
    inputs:
      skaffold:
        type: string
        required: false
        description: "Skaffold Version"
        default: "1.33.0"
    secrets:
      GCP_PROJECT_ID:
        description: "GCP Project ID"
        required: true
      GCP_SERVICE_ACCOUNT:
        description: "GCP Service Account Key"
        required: true
      GKE_CLUSTER:
        description: "GKE Cluster Name"
        required: true
      GKE_LOCATION:
        description: "GKE Cluster Location"
        required: true

jobs:
  build:
    name: Build Docker images
    if: github.event.ref == 'refs/heads/develop' || github.event.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: dist-artifact
          path: dist
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          export_default_credentials: true
          credentials_file_path: "/tmp/2143f99e-4ec1-11ec-9d55-cbf168cabc9e"
      - name: Configure Docker Auth
        run: |
          gcloud --quiet auth configure-docker eu.gcr.io

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: "skaffold"
          skaffold: "${{ inputs.skaffold }}"

      - name: Build
        run: |
          skaffold build

      - name: Push
        run: |
          skaffold build --file-output=build.json

      - name: Archive build reference
        uses: actions/upload-artifact@v2
        with:
          name: build-ref
          path: build.json

  deploy-development:
    name: Deploy to development
    if: github.event.ref == 'refs/heads/develop'
    needs:
      - build
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - uses: google-github-actions/get-gke-credentials@v0.3.0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_LOCATION }}

      - name: Download build reference
        uses: actions/download-artifact@v2
        with:
          name: build-ref

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: skaffold
          skaffold: "${{ inputs.skaffold }}"

      - name: Deploy
        run: |
          skaffold deploy --build-artifacts=build.json

  deploy-production:
    name: Deploy to production
    if: github.event.ref == 'master'
    needs:
      - build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - uses: google-github-actions/get-gke-credentials@v0.3.0
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_LOCATION }}

      - name: Download build reference
        uses: actions/download-artifact@v2
        with:
          name: build-ref

      - uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: skaffold
          skaffold: "${{ inputs.skaffold }}"

      - name: Deploy
        run: |
          skaffold deploy --build-artifacts=build.json
