name: Verify workflows
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup tools cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/bin
          key: "${{ runner.os }}-tools-${{ hashFiles('install-tools') }}"

      - name: Install tools
        if: "!steps.cache.outputs.cache-hit"
        run: |
          ./install-tools

      - name: Verify that workflows are up to date
        run: |
          ./update-workflows
          git diff --exit-code

      - name: Lint workflows
        run: |
          bin/actionlint